#%RAML 1.0
title: phone-verification-api

securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
uses: 
  
  traits-lib: library/library.raml

/verify:
  get:
    securedBy: [basic]
    description: verify the customer phone number.
    queryParameters:
      phoneNumber: 
        type: string
        description: "customer phone number"
        required: true
    responses:
      200:
        description: Every ping is answered with a pong.
        body:
          application/json:
